---
openapi: 3.0.3
info:
  title: onecx-theme themes import from file during the start of the application
  version: 1.0.0
servers:
  - url: "http://localhost"
paths:
  /import/theme:
    post:
      operationId: importTheme
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DataImport'
      responses:
        200:
          description: ok
components:
  schemas:
    DataImport:
      type: object
      properties:
        themes:
          $ref: '#/components/schemas/DataImportThemes'
    DataImportThemes:
      type: object
      nullable: false
      additionalProperties:
        $ref: '#/components/schemas/DataImportTheme'
    DataImportTheme:
      type: object
      properties:
        cssFile:
          type: string
        description:
          type: string
        assetsUrl:
          type: string
        logoUrl:
          type: string
        faviconUrl:
          type: string
        previewImageUrl:
          type: string
        assetsUpdateDate:
          type: string
        properties:
          type: object
