---
openapi: 3.0.3
info:
  title: onecx-theme themes import from file during the start of the application
  version: 1.0.0
servers:
  - url: "http://localhost"
paths:
  /import/theme:
    post:
      operationId: importTheme
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DataImport'
      responses:
        200:
          description: ok
components:
  schemas:
    DataImport:
      type: object
      properties:
        themes:
          $ref: '#/components/schemas/DataImportThemes'
    DataImportThemes:
      type: object
      nullable: false
      additionalProperties:
        $ref: '#/components/schemas/DataImportTheme'
    DataImportTheme:
      type: object
      required:
        - tenantId
      properties:
        tenantId:
          type: string
        cssFile:
          type: string
        description:
          type: string
        assetsUrl:
          type: string
        logoUrl:
          type: string
        faviconUrl:
          type: string
        logoId:
          $ref: '#/components/schemas/Image'
        faviconId:
          $ref: '#/components/schemas/Image'
        previewImageUrl:
          type: string
        assetsUpdateDate:
          type: string
        properties:
          type: object
    Image:
      type: object
      properties:
        imageData:
          type: object
          properties:
            imageBytes:
              type: string
              format: byte
        mimeType:
          type: string
        width:
          type: string
        height:
          type: string
        url:
          type: string
          example: http://onecx-image-svc/data/afcc5d0d-6509-497a-8125-614f82b106ae
        creationDate:
          $ref: '#/components/schemas/OffsetDateTime'
        creationUser:
          type: string
        modificationDate:
          $ref: '#/components/schemas/OffsetDateTime'
        modificationUser:
          type: string
    OffsetDateTime:
      format: date-time
      type: string
      example: 2022-03-10T12:15:50-04:00
