---
openapi: 3.0.3
info:
  title: onecx-theme export and import service v1
  description: This API provides endpoints for exporting and importing themes
  version: 1.0.0
servers:
  - url: "http://onecx-theme-svc:8080"
tags:
  - name: themesExportImport
    description: Exporting and importing Themes
paths:
  /exim/v1/themes/export:
    post:
      security:
        - oauth2: [ ocx-th:all, ocx-th:read ]
      tags:
        - themesExportImport
      description: Export one or multiple themes
      operationId: exportThemes
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ExportThemeRequest'
      responses:
        "200":
          description: Theme exported successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ThemeSnapshot'
        "404":
          description: Themes not found
  /exim/v1/themes/import:
    post:
      security:
        - oauth2: [ ocx-th:all, ocx-th:write ]
      tags:
        - themesExportImport
      description: Import one or multiple themes
      operationId: importThemes
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ThemeSnapshot'
      responses:
        "200":
          description: Themes imported successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ImportThemeResponse'
        "400":
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EximProblemDetailResponse'
  /exim/v1/themes/operator:
    post:
      security:
        - oauth2: [ ocx-th:all, ocx-th:write ]
      tags:
        - themesExportImport
      description: Import themes by the onecx operator only
      operationId: operatorImportThemes
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ThemeSnapshot'
      responses:
        "200":
          description: Theme imported successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ImportThemeResponse'
        "400":
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EximProblemDetailResponse'
components:
  securitySchemes:
    oauth2:
      type: oauth2
      flows:
        clientCredentials:
          tokenUrl: https://oauth.simple.api/token
          scopes:
            ocx-th:all: Grants access to all operations
            ocx-th:read: Grants read access
            ocx-th:write: Grants write access
  schemas:
    ExportThemeRequest:
      type: object
      properties:
        names:
          type: array
          uniqueItems: true
          items:
            type: string
    ThemeSnapshot:
      type: object
      properties:
        id:
          type: string
          minLength: 10
          description: ID of the request
        created:
          $ref: '#/components/schemas/OffsetDateTime'
        themes:
          type: object
          nullable: false
          additionalProperties:
            $ref: '#/components/schemas/EximTheme'
    ImportThemeResponse:
      type: object
      properties:
        id:
          type: string
          minLength: 10
          description: ID of the request
        themes:
          additionalProperties:
            $ref: '#/components/schemas/ImportThemeResponseStatus'
    ImportThemeResponseStatus:
      type: string
      enum:
        - UPDATE
        - CREATED
        - SKIP
    EximTheme:
      type: object
      properties:
        displayName:
          type: string
        cssFile:
          type: string
        description:
          type: string
        assetsUrl:
          type: string
        logoUrl:
          type: string
        smallLogoUrl:
          type: string
        faviconUrl:
          type: string
        previewImageUrl:
          type: string
        assetsUpdateDate:
          type: string
        properties:
          type: object
        overrides:
          type: object
        images:
          $ref: '#/components/schemas/Images'
        mandatory:
          type: boolean
          default: false
    EximProblemDetailResponse:
      type: object
      properties:
        errorCode:
          type: string
        detail:
          type: string
        params:
          type: array
          items:
            $ref: '#/components/schemas/EximProblemDetailParam'
        invalidParams:
          type: array
          items:
            $ref: '#/components/schemas/EximProblemDetailInvalidParam'
    EximProblemDetailParam:
      type: object
      properties:
        key:
          type: string
        value:
          type: string
    EximProblemDetailInvalidParam:
      type: object
      properties:
        name:
          type: string
        message:
          type: string
    OffsetDateTime:
      format: date-time
      type: string
      example: 2022-03-10T12:15:50-04:00
    Images:
      type: object
      nullable: false
      additionalProperties:
        $ref: '#/components/schemas/Image'
    Image:
      type: object
      properties:
        imageData:
          type: string
          format: byte
        mimeType:
          type: string