---
openapi: 3.0.3
info:
  title: onecx-theme internal service
  version: 1.0.0
servers:
  - url: "http://onecx-theme-svc:8080"
tags:
  - name: themes
paths:
  /v1/themes:
    get:
      tags:
        - themes
      description: Get list of all themes
      operationId: getThemesInfo
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ThemeInfoList'
        "404":
          description: Not found
  /v1/themes/{name}:
    get:
      tags:
        - themes
      description: Load a single theme definition
      operationId: getThemeByName
      parameters:
        - name: name
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Theme'
        "404":
          description: Not found
  /v1/themes/{name}/favicon:
    get:
      tags:
        - themes
      description: Load a single theme definition
      operationId: getThemeFaviconByName
      parameters:
        - name: name
          in: path
          required: true
          schema:
            type: string
      responses:
        200:
          description: OK
          content:
            image/*:
              schema:
                minimum: 1
                maximum: 20000
                type: string
                format: binary
        404:
          description: Not found
components:
  schemas:
    ThemeInfoList:
      type: object
      properties:
        themes:
          type: array
          items:
            $ref: '#/components/schemas/ThemeInfo'
    ThemeInfo:
      type: object
      properties:
        name:
          minLength: 2
          type: string
        description:
          type: string
    Theme:
      required:
        - name
      type: object
      properties:
        name:
          minLength: 2
          type: string
        cssFile:
          type: string
        description:
          type: string
        assetsUrl:
          type: string
        logoUrl:
          type: string
        faviconUrl:
          type: string
        previewImageUrl:
          type: string
        assetsUpdateDate:
          type: string
        properties:
          type: object