---
openapi: 3.0.3
info:
  title: Onecx-theme internal image service
  description: This API provides endpoints to manage images of themes
  version: 1.0.0
servers:
  - url: "http://onecx-theme-svc:8080"
tags:
  - name: imagesInternal
    description: Manage Images
paths:
  /internal/images/{refId}/{refType}:
    get:
      security:
        - oauth2: [ ocx-th:all, ocx-th:read ]
      tags:
        - imagesInternal
      description: Get an image by its reference id and type
      operationId: getImage
      parameters:
        - name: refId
          in: path
          required: true
          schema:
            type: string
        - name: refType
          in: path
          required: true
          schema:
            $ref: "#/components/schemas/RefType"
      responses:
        "200":
          description: Image retrieved successfully
          content:
            image/*:
              schema:
                minimum: 1
                maximum: 110000
                type: string
                format: binary
        "400":
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetailResponse'
    delete:
      security:
        - oauth2: [ ocx-th:all, ocx-th:delete ]
      tags:
        - imagesInternal
      description: Delete an image by its reference id and type
      operationId: deleteImage
      parameters:
        - name: refId
          in: path
          required: true
          schema:
            type: string
        - name: refType
          in: path
          required: true
          schema:
            $ref: "#/components/schemas/RefType"
      responses:
        "200":
          description: Image deleted successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ImageInfo'
        "400":
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetailResponse'
    post:
      security:
        - oauth2: [ ocx-th:all, ocx-th:write ]
      tags:
        - imagesInternal
      description: Upload an images by its reference id and type
      parameters:
        - in: header
          name: Content-Length
          required: true
          schema:
            minimum: 1
            maximum: 110000
            type: integer
        - name: refId
          in: path
          required: true
          schema:
            type: string
        - name: refType
          in: path
          required: true
          schema:
            $ref: "#/components/schemas/RefType"
        - name: mimeType
          in: header
          required: true
          schema:
            $ref: "#/components/schemas/MimeType"
      operationId: uploadImage
      requestBody:
        required: true
        content:
          image/*:
            schema:
              minimum: 1
              maximum: 110000
              type: string
              format: binary
      responses:
        "201":
          description: Image uploaded successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ImageInfo'
        "400":
          description: Bad Request
  /internal/images/{refId}:
    delete:
      security:
        - oauth2: [ ocx-th:all, ocx-th:delete ]
      tags:
        - imagesInternal
      description: Delete an image by its reference id
      operationId: deleteImagesById
      parameters:
        - name: refId
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Image deleted successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ImageInfo'
        "400":
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetailResponse'
components:
  securitySchemes:
    oauth2:
      type: oauth2
      flows:
        clientCredentials:
          tokenUrl: https://oauth.simple.api/token
          scopes:
            ocx-th:all: Grants access to all operations
            ocx-th:read: Grants read access
            ocx-th:write: Grants write access
            ocx-th:delete: Grants access to delete operations
  schemas:
    MimeType:
      type: string
      enum: [ "image/x-icon", "image/png", "image/jpg", "image/jpeg" ]
    RefType:
      type: string
      enum: [ logo, logo-small, favicon ]
    ImageInfo:
      type: object
      properties:
        id:
          type: string
    ProblemDetailResponse:
      type: object
      properties:
        errorCode:
          type: string
        detail:
          type: string
        params:
          type: array
          items:
            $ref: '#/components/schemas/ProblemDetailParam'
        invalidParams:
          type: array
          items:
            $ref: '#/components/schemas/ProblemDetailInvalidParam'
    ProblemDetailParam:
      type: object
      properties:
        key:
          type: string
        value:
          type: string
    ProblemDetailInvalidParam:
      type: object
      properties:
        name:
          type: string
        message:
          type: string