---
openapi: 3.0.3
info:
  title: onecx-theme internal template import service
  description: This API provides endpoints for themes import from file during the start of the application
  version: 1.0.0
servers:
  - url: "http://localhost"
paths:
  /import/theme:
    post:
      security:
        - oauth2: [ ocx-th:write ]
      operationId: importTheme
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TemplateImport'
      responses:
        200:
          description: Template imported successfully
components:
  securitySchemes:
    oauth2:
      type: oauth2
      flows:
        clientCredentials:
          tokenUrl: https://oauth.simple.api/token
          scopes:
            ocx-th:write: Grants write access
  schemas:
    TemplateImport:
      type: object
      properties:
        themes:
          $ref: '#/components/schemas/TemplateThemes'
    TemplateThemes:
      type: object
      nullable: false
      additionalProperties:
        $ref: '#/components/schemas/TemplateTheme'
    TemplateTheme:
      type: object
      required:
        - tenantId
      properties:
        cssFile:
          type: string
        description:
          type: string
        assetsUrl:
          type: string
        logoUrl:
          type: string
        faviconUrl:
          type: string
        images:
          $ref: '#/components/schemas/TemplateImages'
        previewImageUrl:
          type: string
        assetsUpdateDate:
          type: string
        properties:
          type: object
        mandatory:
          type: boolean
          default: false
    TemplateImages:
      type: object
      nullable: false
      additionalProperties:
        $ref: '#/components/schemas/TemplateImage'
    TemplateImage:
      type: object
      properties:
        imageData:
          type: string
          format: byte
        mimeType:
          type: string
