---
openapi: 3.0.3
info:
  title: onecx-theme external service V1
  description: This API provides endpoints to retrieve Themes and Images
  version: 1.0.0
servers:
  - url: "http://onecx-theme-svc:8080"
tags:
  - name: themes
    description: Retrieve Themes and Images
paths:
  /v1/themes:
    get:
      security:
        - oauth2: [ ocx-th:read ]
      tags:
        - themes
      description: Get a list of all themes
      operationId: getThemesInfo
      responses:
        "200":
          description: Themes retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ThemeInfoList'
        "404":
          description: Themes not found
  /v1/themes/{name}:
    get:
      security:
        - oauth2: [ ocx-th:read ]
      tags:
        - themes
      description: Get a single theme by its name
      operationId: getThemeByName
      parameters:
        - name: name
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Theme retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Theme'
        "404":
          description: Theme not found
  /v1/themes/{name}/favicon:
    get:
      security:
        - oauth2: [ ocx-th:read ]
      tags:
        - themes
      description: Get the favicon of a theme by its name
      operationId: getThemeFaviconByName
      parameters:
        - name: name
          in: path
          required: true
          schema:
            type: string
      responses:
        200:
          description: Favicon retrieved successfully
          content:
            image/*:
              schema:
                minimum: 1
                maximum: 110000
                type: string
                format: binary
        404:
          description: Favicon not found
  /v1/themes/{name}/logo:
    get:
      security:
        - oauth2: [ ocx-th:read ]
      tags:
        - themes
      description: Get a logo of a theme by its name
      operationId: getThemeLogoByName
      parameters:
        - name: name
          in: path
          required: true
          schema:
            type: string
        - name: small
          in: query
          required: false
          schema:
            type: boolean
            default: false
      responses:
        200:
          description: Logo retrieved successfully
          content:
            image/*:
              schema:
                minimum: 1
                maximum: 110000
                type: string
                format: binary
        404:
          description: Logo not found
components:
  securitySchemes:
    oauth2:
      type: oauth2
      flows:
        clientCredentials:
          tokenUrl: https://oauth.simple.api/token
          scopes:
            ocx-th:read: Grants read access
  schemas:
    ThemeInfoList:
      type: object
      properties:
        themes:
          type: array
          items:
            $ref: '#/components/schemas/ThemeInfo'
    ThemeInfo:
      type: object
      properties:
        name:
          minLength: 2
          type: string
        description:
          type: string
    Theme:
      required:
        - name
      type: object
      properties:
        displayName:
          type: string
        name:
          minLength: 2
          type: string
        cssFile:
          type: string
        description:
          type: string
        assetsUrl:
          type: string
        logoUrl:
          type: string
        faviconUrl:
          type: string
        previewImageUrl:
          type: string
        assetsUpdateDate:
          type: string
        properties:
          type: object