openapi: 3.0.3
info:
  title: onecx-theme image import from file during the start of the application
  version: 1.0.0
servers:
  - url: "http://localhost"
paths:
  /v1/images:
    post:
      tags:
        - imageV1
      description: Upload Images
      operationId: uploadImage
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                image:
                  format: binary
                  description: file data
                  type: string
                fileName:
                  type: string
            encoding:
              image:
                contentType: application/octet-stream
              fileName:
                contentType: text/plain
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ImageInfoDTOv1'
        "401":
          description: Unauthorized
        "403":
          description: Not Authorized
        "500":
          description: Internal Server Error
      security:
        - SecurityScheme:
            - onecx-portal-user
            - onecx-portal-admin
            - onecx-portal-super-admin
        - SecurityScheme:
            - onecx-portal-user
            - onecx-portal-admin
            - onecx-portal-super-admin
  /v1/images/{imageId}:
    get:
      tags:
        - imageV1
      description: Upload Images
      operationId: getImage
      parameters:
        - name: imageId
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ImageInfoDTOv1'
        "500":
          description: Internal Server Error
        "401":
          description: Not Authorized
        "403":
          description: Not Allowed
      security:
        - SecurityScheme:
            - onecx-portal-user
            - onecx-portal-admin
            - onecx-portal-super-admin
        - SecurityScheme:
            - onecx-portal-user
            - onecx-portal-admin
            - onecx-portal-super-admin
    delete:
      tags:
        - imageV1
      description: Delete Image
      operationId: deleteImage
      parameters:
        - name: imageId
          in: path
          required: true
          schema:
            type: string
      responses:
        "204":
          description: No Content
        "401":
          description: Unauthorized
        "403":
          description: Not Authorized
        "500":
          description: Internal Server Error
      security:
        - SecurityScheme:
            - onecx-portal-user
            - onecx-portal-admin
            - onecx-portal-super-admin
        - SecurityScheme:
            - onecx-portal-user
            - onecx-portal-admin
            - onecx-portal-super-admin
components:
  schemas:
    ImageInfoDTOv1:
      type: object
      properties:
        version:
          format: int32
          type: integer
        creationDate:
          $ref: '#/components/schemas/OffsetDateTime'
        creationUser:
          type: string
        modificationDate:
          $ref: '#/components/schemas/OffsetDateTime'
        modificationUser:
          type: string
        id:
          type: string
        userUploaded:
          description: flag whether Image was uploaded by user
          type: boolean
        lastUpdateTime:
          allOf:
            - $ref: '#/components/schemas/OffsetDateTime'
            - description: dateTime of last update
        imageUrl:
          type: string
          example: http://onecx-image-svc/data/afcc5d0d-6509-497a-8125-614f82b106ae
        smallImageUrl:
          type: string
          example: http://onecx-image-svc/data/afcc5d0d-6509-497a-8125-614f82asb106ae
    OffsetDateTime:
      format: date-time
      type: string
      example: 2022-03-10T12:15:50-04:00
    Image:
      type: object
      properties:
        height:
          type: integer
          format: int32
          description: Height of the image
        width:
          type: integer
          format: int32
          description: Width of the image
        mimeType:
          type: string
          description: MIME type of the image
        image:
          type: string
          format: binary
          description: Image file data